name: Build and Push Docker Image - Games

on:
  push:
    branches: [ "main" ]  # dispara quando você faz push na main
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do código
      uses: actions/checkout@v4

    - name: Configurar .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'
        
    - name: Configurar acesso ao GitHub Packages
      run: |
        dotnet nuget remove source github || true
        dotnet nuget add source https://nuget.pkg.github.com/AlanQ139/index.json \
          --name github \
          --username AlanQ139 \
          --password ${{ secrets.GITHUB_TOKEN }} \
          --store-password-in-clear-text

    - name: Restaurar dependências
      run: dotnet restore

    - name: Build do projeto
      run: dotnet build --configuration Release --no-restore

    - name: Rodar testes 
      run: dotnet test --no-build --verbosity normal

    - name: Login no Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build da imagem Docker
      run: docker build -t alqueiroz/users:latest -t alqueiroz/users:1.0 .

    - name: Push da imagem no Docker Hub
      run: |
        docker push alqueiroz/users:latest
        docker push alqueiroz/users:1.0
